
services:
    # Mysql database container
    db:
        image: mysql
        container_name: symfony_myBank
        restart: always
        environment:
            MYSQL_DATABASE: myBank
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
            MYSQL_ROOT_PASSWORD: root
        volumes:
          - db-data:/var/lib/mysql
        networks:
            - symfony
    # phpmyadmin container
    phpmyadmin:
        image: phpmyadmin
        depends_on:
            - db
        ports:
            - 8081:80
        environment:
            PMA_HOST: db
        networks:
            - symfony

    # Symfony apache project container
    www:
        build: 
          context: .
          dockerfile: Dockerfile
        container_name: symfony-myBank
        ports:
          - "8741:80"
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www/project
        restart: always
        networks:
            - symfony
    jenkins:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: jenkins-agent-mybank
        volumes:
          - .:/var/www/project
        networks:
            - symfony


networks:
    symfony:

volumes:
    db-data: