
services:
    # Mysql database container
    db:
        image: mysql
        container_name: symfony_myBanck
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - symfony

    # phpmyadmin container
    phpmyadmin:
        image: phpmyadmin
        container_name: tutorial_phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - symfony

    # Symfony apache project container
    www:
        build: 
          context: .
          dockerfile: Dockerfile
        container_name: symfony-myBank
        ports:
          - "8741:80"
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www/project
        restart: always
        networks:
            - symfony

networks:
    symfony:

volumes:
    db-data: